language: en

#pipeline: supervised_embeddings

pipeline:
- name: "WhitespaceTokenizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
- name: "EmbeddingIntentClassifier"
- name: "DucklingHTTPExtractor"
  url: "http://duckling:8000"
  locale: "NL_Nothing"
  # dimensions to extract
  dimensions: ["time", "number", "amount-of-money", "distance"]

policies:
  - name: KerasPolicy
    epochs: 200
    batch_size: 50
    max_training_samples: 300
  - name: FallbackPolicy
  - name: MemoizationPolicy
  - name: MappingPolicy
    
