version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest-full
    ports:
      - 5002:5005
    volumes:
      - ./:/app
    command:
      - run  
      - --cors
      - "http://localhost:4200"
      - --enable-api
      - --debug
  action_server:
    image: rasa/rasa-sdk:latest
    volumes:
      - ./actions:/app/actions
  duckling:
    image: rasa/duckling:latest 
    ports:
        - "8000:8000"
 