version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest-full
    ports:
      - 5002:5005
    volumes:
      - ./:/app
    command:
      - run  
      - --cors
      - "http://localhost:4200"
      - --enable-api
      - --debug
      - --endpoints
      - endpoints.yml
      - --credentials
      - credentials.yml
  action_server:
    image: rasa/rasa-sdk:latest
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions
